# Generated by Django 4.2.4 on 2025-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('ADMIN', 'Admin')], default='LEARNER', max_length=20),
        ),
    ]
